services:
  vector-db:
    image: pgvector/pgvector:pg16
    container_name: rag_vector_db_local
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password_dev
      - POSTGRES_DB=rag_knowledge_base
    volumes:
      - pg_data_local:/var/lib/postgresql/data
    networks:
      - rag_net

  backend:
    build: .
    container_name: rag_api_local
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # 1. ESTA LÍNEA TE DEJA VER LOS LOGS
      - PYTHONUNBUFFERED=1
      # Conexión interna de Docker
      - POSTGRES_HOST=vector-db
      - POSTGRES_USER=rag_user
      # 2. CORREGIDO: Debe coincidir con la DB del servicio vector-db
      - POSTGRES_DB=rag_knowledge_base
    depends_on:
      - vector-db
    networks:
      - rag_net
    # 3. VOLUMEN DE DESARROLLO (Espejo):
    # Esto hace que tus cambios en VS Code se reflejen adentro sin rebuild
    volumes:
      - .:/code

volumes:
  pg_data_local:

networks:
  rag_net:
    driver: bridge
